name: lms_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project with Serverpod.
environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies: 
  serverpod_flutter: 1.2.5
  serverpod_auth_shared_flutter: 1.2.5
  serverpod_auth_email_flutter: 1.2.5
  cupertino_icons: ^1.0.5
  get: 4.6.6
  flutter: 
    sdk: flutter
  lms_client: 
    path: ../lms_client

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

